version: "3"

services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
    working_dir: /
    ports:
      - "3306:3306"
    command: bash -c "rm -rf /app && mkdir /app && git clone https://github.com/Romario-Stankovic/Student_Testing_Platform_API /app/backend/ && cd /app/backend && mysql -uroot -proot < ./database/testing_platform_empty.sql"

  backend:
    image: node:16.14.0
    working_dir: /
    depends_on:
      - mysql
    command: bash -c "rm -rf /app && mkdir /app && git clone https://github.com/Romario-Stankovic/Student_Testing_Platform_API /app/backend/ && cd /app/backend && npm i && npm run start"