version: "3"

services:

  init:
    image: alpine
    container_name: init
    working_dir: /shared
    command: sh -c "apk add git && rm -rf /shared/app && git clone https://github.com/Romario-Stankovic/Student_Testing_Platform_API /shared/app"
    volumes:
      - shared:/shared

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=student_testing_platform
    working_dir: /
    depends_on:
      - init
    ports:
      - "3306:3306"
    volumes:
      - shared:/shared

  backend:
    image: node:16.14.0
    container_name: backend
    working_dir: /
    depends_on:
      - init
      - mysql
    command: /shared/docker/run-backend.sh
    volumes:
      - shared:/shared

volumes:
  shared: